### ISSUE TITLE
Issues editing data columns in the UI

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#339]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5930594451

---

## Describe the bug

I cannot remove a data column in the UI

## To reproduce

1. Go to  the build page of any node
2. Click on _Edit_ in section 5.
3. Click _Remove_ beside a data column
5. see that the column is not removed

## Expected behaviour

Clicking the remove button removes the column.

## Additional context

When I check the logs, here is the error I get:

Message: `php`

Location: `/node/14/edit?_wrapper_format=drupal_ajax&ajax_form=1&destination=%2Fnode%2F14%2Fbuild&display=section_5`

Referrer: `/node/14/edit?display=section_5&destination=/node/14/build`

Severity: `error`

Backtrace

```
#0 /var/www/html/html/modules/custom/bc_dc/bc_dc.module(798): array_keys(NULL)
#1 /var/www/html/html/core/lib/Drupal/Core/Extension/ModuleHandler.php(545): bc_dc_field_widget_single_element_paragraphs_form_alter(Array, Object(Drupal\Core\Form\FormState), Array)
#2 /var/www/html/html/core/lib/Drupal/Core/Field/WidgetBase.php(459): Drupal\Core\Extension\ModuleHandler->alter('field_widget_si...', Array, Object(Drupal\Core\Form\FormState), Array)
#3 /var/www/html/html/modules/contrib/paragraphs/src/Plugin/Field/FieldWidget/ParagraphsWidget.php(1353): Drupal\Core\Field\WidgetBase->formSingleElement(Object(Drupal\entity_reference_revisions\EntityReferenceRevisionsFieldItemList), 0, Array, Array, Object(Drupal\Core\Form\FormState))
#4 /var/www/html/html/core/lib/Drupal/Core/Field/WidgetBase.php(117): Drupal\paragraphs\Plugin\Field\FieldWidget\ParagraphsWidget->formMultipleElements(Object(Drupal\entity_reference_revisions\EntityReferenceRevisionsFieldItemList), Array, Object(Drupal\Core\Form\FormState))
#5 /var/www/html/html/modules/contrib/paragraphs/src/Plugin/Field/FieldWidget/ParagraphsWidget.php(1475): Drupal\Core\Field\WidgetBase->form(Object(Drupal\entity_reference_revisions\EntityReferenceRevisionsFieldItemList), Array, Object(Drupal\Core\Form\FormState), NULL)
#6 /var/www/html/html/core/lib/Drupal/Core/Entity/Entity/EntityFormDisplay.php(186): Drupal\paragraphs\Plugin\Field\FieldWidget\ParagraphsWidget->form(Object(Drupal\entity_reference_revisions\EntityReferenceRevisionsFieldItemList), Array, Object(Drupal\Core\Form\FormState))
#7 /var/www/html/html/core/lib/Drupal/Core/Entity/ContentEntityForm.php(121): Drupal\Core\Entity\Entity\EntityFormDisplay->buildForm(Object(Drupal\node\Entity\Node), Array, Object(Drupal\Core\Form\FormState))
#8 /var/www/html/html/core/modules/node/src/NodeForm.php(127): Drupal\Core\Entity\ContentEntityForm->form(Array, Object(Drupal\Core\Form\FormState))
#9 /var/www/html/html/core/lib/Drupal/Core/Entity/EntityForm.php(107): Drupal\node\NodeForm->form(Array, Object(Drupal\Core\Form\FormState))
#10 [internal function]: Drupal\Core\Entity\EntityForm->buildForm(Array, Object(Drupal\Core\Form\FormState))
#11 /var/www/html/html/core/lib/Drupal/Core/Form/FormBuilder.php(536): call_user_func_array(Array, Array)
#12 /var/www/html/html/core/lib/Drupal/Core/Form/FormBuilder.php(375): Drupal\Core\Form\FormBuilder->retrieveForm('node_data_set_e...', Object(Drupal\Core\Form\FormState))
#13 /var/www/html/html/core/lib/Drupal/Core/Form/FormBuilder.php(633): Drupal\Core\Form\FormBuilder->rebuildForm('node_data_set_e...', Object(Drupal\Core\Form\FormState), Array)
#14 /var/www/html/html/core/lib/Drupal/Core/Form/FormBuilder.php(325): Drupal\Core\Form\FormBuilder->processForm('node_data_set_e...', Array, Object(Drupal\Core\Form\FormState))
#15 /var/www/html/html/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\node\NodeForm), Object(Drupal\Core\Form\FormState))
#16 /var/www/html/html/core/modules/layout_builder/src/Controller/LayoutBuilderHtmlEntityFormController.php(39): Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch))
#17 [internal function]: Drupal\layout_builder\Controller\LayoutBuilderHtmlEntityFormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch))
#18 /var/www/html/html/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#19 /var/www/html/html/core/lib/Drupal/Core/Render/Renderer.php(627): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#20 /var/www/html/html/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#21 /var/www/html/html/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#22 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(181): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#23 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#24 /var/www/html/html/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#25 /var/www/html/html/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#26 /var/www/html/html/core/lib/Drupal/Core/StackMiddleware/ContentLength.php(28): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#27 /var/www/html/html/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\ContentLength->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#28 /var/www/html/html/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#29 /var/www/html/html/modules/contrib/shield/src/ShieldMiddleware.php(270): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#30 /var/www/html/html/modules/contrib/shield/src/ShieldMiddleware.php(137): Drupal\shield\ShieldMiddleware->bypass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#31 /var/www/html/html/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\shield\ShieldMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#32 /var/www/html/html/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#33 /var/www/html/html/core/lib/Drupal/Core/StackMiddleware/AjaxPageState.php(36): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#34 /var/www/html/html/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\AjaxPageState->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#35 /var/www/html/html/core/lib/Drupal/Core/DrupalKernel.php(704): Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#36 /var/www/html/html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#37 {main}
```

---

## DOD

- [x] I can remove a column without error

**Comment by CraigClark** [comment]
Resolved. tested on https://test.cat.data.fin.gov.bc.ca
