### ISSUE TITLE
Varnish cache server errors on some admin pages

### ISSUE THREAD

**Issue by danhgov** [bcgov/MFIN-Data-Catalogue#533]
As noted in #508, some admin pages are getting a Varnish error:
> ![image](https://github.com/user-attachments/assets/989f14d0-7bb1-495e-b0f9-d21a469afad7)

I've seen it on these two pages: 

- [Structure... Pages](https://test.cat.data.fin.gov.bc.ca/admin/structure/page_manager)
- [Configuration... Development... Default Content Deploy... Export](https://test.cat.data.fin.gov.bc.ca/admin/config/development/dcd/export)

On Dev and Prod, I saw this error only for the latter of those two items -- on Test, it's for both of them.

I haven't looked hard -- there may be lots more instances of this.

A clear-cache didn't fix it.

**Comment by NicoledeGreef** [comment]
The Varnish cache error is now manifesting in each environment when a user tries to download a data dictionary from a metadata record.  Reported by a user in Production so will be prioritized accordingly.

![Image](https://github.com/user-attachments/assets/e9b4aa40-c3f9-476d-8376-6c578eea4583)

Logs say:

![Image](https://github.com/user-attachments/assets/fd678dd7-a2b4-4b99-affa-3037625d090d)


#0 /var/www/html/modules/custom/bc_dc/src/Controller/BcDcCreateFileController.php(127): PhpOffice\PhpSpreadsheet\Spreadsheet->addSheet(Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet))
#1 [internal function]: Drupal\bc_dc\Controller\BcDcCreateFileController->createFile(Object(Drupal\node\Entity\Node), 'xlsx')
#2 /var/www/html/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#3 /var/www/html/core/lib/Drupal/Core/Render/Renderer.php(638): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#4 /var/www/html/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(121): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#5 /var/www/html/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#6 /var/www/vendor/symfony/http-kernel/HttpKernel.php(181): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#7 /var/www/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#8 /var/www/html/core/lib/Drupal/Core/StackMiddleware/Session.php(53): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /var/www/html/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /var/www/html/core/lib/Drupal/Core/StackMiddleware/ContentLength.php(28): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /var/www/html/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\ContentLength->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/www/html/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /var/www/html/modules/contrib/shield/src/ShieldMiddleware.php(263): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /var/www/html/modules/contrib/shield/src/ShieldMiddleware.php(130): Drupal\shield\ShieldMiddleware->bypass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /var/www/html/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\shield\ShieldMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /var/www/html/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /var/www/html/core/lib/Drupal/Core/StackMiddleware/AjaxPageState.php(36): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /var/www/html/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\AjaxPageState->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 /var/www/html/core/lib/Drupal/Core/DrupalKernel.php(741): Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#20 /var/www/html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#21 {main}

**Comment by chrislaick** [comment]
A little more on this error. The varnish cache error will manifest and look like the same error, but it's often caused by different things. In this case, there was an issue with the bc_dc controller. It was trying to add a new worksheet to the PhpSpreadsheet object, but it already contained a default worksheet named "Worksheet".

Deployed to DEV and TEST. @NicoledeGreef @david-fong-bc

**Comment by david-fong-bc** [comment]
Download of CSV and XLSX data dictionary is now working for me on DEV and TEST. Thanks, Chris!

**Comment by chrislaick** [comment]
Deployed to PROD. @NicoledeGreef @david-fong-bc

**Comment by NicoledeGreef** [comment]
Thank you @chrislaick
